install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build

test_script:
  - SET RUST_LOG=mio=trace,mio_win_inv,test & SET RUST_TEST_THREADS=1& cargo test --verbose
